import Head from "next/head";

export default function PageLayout({
  title,
  children,
  mainStyles = [],
  useDefaultStyles = true
}) {
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <style>{`
      
        .mainContainer {
          width: 100%;
          height: 100%;
          position: fixed;
          top: 0;
          left: 0;
          display: flex;
          justify-content: center;
          flex-direction: column;
          transition: all 1s;
          overflow: auto;
  
        }
      `}</style>
      <main
        className={[
          useDefaultStyles ? "mainContainer" : "",
          ...mainStyles
        ].join(" ")}
      >
        {children}
      </main>
    </>
  );
}
